-- Demo Portal - Infrastructure Setup
-- Creates database, schema, warehouse, compute pool, image repository, and stages

CREATE DATABASE IF NOT EXISTS __DATABASE__;
CREATE SCHEMA IF NOT EXISTS __DATABASE__.__SCHEMA__;

CREATE WAREHOUSE IF NOT EXISTS __WAREHOUSE__
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

CREATE COMPUTE POOL IF NOT EXISTS __COMPUTE_POOL__
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 3600;

CREATE IMAGE REPOSITORY IF NOT EXISTS __DATABASE__.__SCHEMA__.PORTAL_REPO;

CREATE STAGE IF NOT EXISTS __DATABASE__.__SCHEMA__.IMAGES_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS __DATABASE__.__SCHEMA__.SCRIPTS_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE);
