-- Demo Portal - Service User and Role
-- Creates a dedicated service user with least-privilege role

USE WAREHOUSE __WAREHOUSE__;

CREATE ROLE IF NOT EXISTS DEMO_PORTAL_ROLE;

CREATE USER IF NOT EXISTS DEMO_PORTAL_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = DEMO_PORTAL_ROLE
  DEFAULT_WAREHOUSE = __WAREHOUSE__;

GRANT ROLE DEMO_PORTAL_ROLE TO USER DEMO_PORTAL_SVC;

-- Database and schema access
GRANT USAGE ON DATABASE __DATABASE__ TO ROLE DEMO_PORTAL_ROLE;
GRANT USAGE ON SCHEMA __DATABASE__.__SCHEMA__ TO ROLE DEMO_PORTAL_ROLE;

-- Table access
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE __DATABASE__.__SCHEMA__.DEMOS TO ROLE DEMO_PORTAL_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE __DATABASE__.__SCHEMA__.SETTINGS TO ROLE DEMO_PORTAL_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE __DATABASE__.__SCHEMA__.DEMO_SESSIONS TO ROLE DEMO_PORTAL_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE __DATABASE__.__SCHEMA__.DEMO_USAGE_LOG TO ROLE DEMO_PORTAL_ROLE;

-- Stage access
GRANT READ, WRITE ON STAGE __DATABASE__.__SCHEMA__.IMAGES_STAGE TO ROLE DEMO_PORTAL_ROLE;
GRANT READ, WRITE ON STAGE __DATABASE__.__SCHEMA__.SCRIPTS_STAGE TO ROLE DEMO_PORTAL_ROLE;

-- Warehouse access
GRANT USAGE, OPERATE ON WAREHOUSE __WAREHOUSE__ TO ROLE DEMO_PORTAL_ROLE;

-- Task scheduling (auto start/stop services on CRON)
GRANT CREATE TASK ON SCHEMA __DATABASE__.__SCHEMA__ TO ROLE DEMO_PORTAL_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DEMO_PORTAL_ROLE;

-- Account-wide visibility for discovering SPCS services and Streamlit apps.
-- This allows SHOW SERVICES IN ACCOUNT and SHOW STREAMLITS IN ACCOUNT.
GRANT ROLE ACCOUNTADMIN TO ROLE DEMO_PORTAL_ROLE;

-- Procedure access
GRANT USAGE ON PROCEDURE __DATABASE__.__SCHEMA__.GRANT_DEMO_ACCESS(VARCHAR, VARCHAR) TO ROLE DEMO_PORTAL_ROLE;

-- Secret access (granted after secret creation in setup.sh)
-- GRANT READ ON SECRET __DATABASE__.__SCHEMA__.PORTAL_PRIVATE_KEY_SECRET TO ROLE DEMO_PORTAL_ROLE;
