-- Demo Portal - Network Rules and External Access Integration
-- Allows the SPCS container to reach Snowflake APIs and S3 stages

CREATE OR REPLACE NETWORK RULE __DATABASE__.__SCHEMA__.SNOWFLAKE_API_RULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ('__SNOWFLAKE_HOST__:443', '__S3_HOST__:443');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DEMO_PORTAL_EXTERNAL_ACCESS
  ALLOWED_NETWORK_RULES = (__DATABASE__.__SCHEMA__.SNOWFLAKE_API_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (__DATABASE__.__SCHEMA__.PORTAL_PRIVATE_KEY_SECRET)
  ENABLED = TRUE;
